### ISSUE TITLE
Robot tests failing due to `unexpected keyword argument 'executable_path'`

### ISSUE THREAD

**Issue by krassowski** [jupyter-lsp/jupyterlab-lsp#956]
Acceptance tests are failing as seen in #955 and #949, although #953 last month was passing.

```
Parent suite setup failed:
TypeError: __init__() got an unexpected keyword argument 'executable_path'
```

It is only used in:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/ff8b6c44d5a81a7bc051604ea37a5bc4da6ec94a/atest/Keywords.resource#L130-L133

Which is confusing as documentation says that it is supported: https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html

It is probably due to https://github.com/robotframework/SeleniumLibrary/pull/1848 but I do not follow this really, that PR has many lines commented out and is not really clear on what it does.

**Comment by bollwyvl** [comment]
Nickle fix:

selenium < 4.10

The full story is complicated

**Comment by krassowski** [comment]
Thank you for a quick reply! I added a pin in https://github.com/jupyter-lsp/jupyterlab-lsp/pull/949 for now.
